@startuml Password

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class Password {
    - _value: string
    ---
    - Password(value: string)
    + {static} create(value: string): Password
    - validate(value: string): void
    + equals(other: Password): boolean
    + get value(): string
}

@enduml
