@startuml PasswordHash

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class PasswordHash {
    - _value: string
    ---
    - PasswordHash(value: string)
    + {static} create(value: string): PasswordHash
    - validate(value: string): void
    + equals(other: PasswordHash): boolean
    + get value(): string
}

@enduml
