@startuml JwtPayload

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class JwtPayload {
      sub: string;
      email: string;
      iat?: number;
      exp?: number;
}

@enduml
