@startuml AddRepositoryCollectionUseCase
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface AddRepositoryCollectionUseCase {
    + execute(command: AddRepositoryCollectionCommand): Promise<AddRepositoryCollectionResult>
}

AddRepositoryCollectionUseCase --right-> AddRepositoryCollectionCommand
AddRepositoryCollectionUseCase --right-> AddRepositoryCollectionResult
@enduml