@startuml GetAllRepositoryCollectionsUseCase
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface GetAllRepositoryCollectionsUseCase {
    + executeAll(command: GetAllRepositoryCollectionsCommand): Promise<GetAllRepositoryCollectionsResult>
}

GetAllRepositoryCollectionsUseCase --right-> GetAllRepositoryCollectionsCommand
GetAllRepositoryCollectionsUseCase --right-> GetAllRepositoryCollectionsResult
@enduml