@startuml GetAllAnalysesForUserUseCase
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GetAllAnalysesForUserUseCase <<Interface>> {
    + getAllAnalysesForUser(command: GetAllAnalysesForUserCommand): Promise<GetAllAnalysesForUserResult>
}

GetAllAnalysesForUserUseCase --down-> GetAllAnalysesForUserCommand
GetAllAnalysesForUserUseCase --down-> GetAllAnalysesForUserResult
@enduml