@startuml NewPatUseCase
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class NewPatUseCase <<Interface>> {
    + execute(command: NewPatCommand): Promise<NewPatResult>
}

NewPatUseCase --down-> NewPatCommand
NewPatUseCase --down-> NewPatResult
@enduml