@startuml StartAnalysisUseCase
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class StartAnalysisUseCase <<Interface>> {
    + execute(command: StartAnalysisCommand): Promise<StartAnalysisResult>
}

StartAnalysisUseCase --down-> StartAnalysisCommand
StartAnalysisUseCase --down-> StartAnalysisResult
@enduml