@startuml UpdatePatUseCase
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface UpdatePatUseCase {
    + execute(command: UpdatePatCommand): Promise<UpdatePatResult>
}

UpdatePatUseCase --right-> UpdatePatCommand
UpdatePatUseCase --right-> UpdatePatResult
@enduml