@startuml MongoDBAdapter
skinparam componentStyle uml2.5
' ECCO LA MAGIA: Sviluppa da sinistra a destra
skinparam linetype ortho
left to right direction 
' Riduciamo un po' lo spazio verticale tra i nodini per non farlo diventare troppo alto
skinparam nodesep 20 
skinparam ranksep 60
skinparam ClassAttributeIconSize 0
hide circles
hide interface methods

interface IGitCredentialReadPort
interface IGitCredentialSavePort
interface IGitCredentialDeletePort
interface IGitCredentialUpdatePort
interface IGitHubAnalysisSavePort
interface IDocsReportSavePort
interface ISecurityReportSavePort
interface IUpdateAnalysisPort
interface IGetAnalysisFromIdPort
interface IGetAllAnalysesForUserPort
interface ICollectionDuplicateCheckerPort
interface ICollectionAdderPort
interface IGetRepositoryCollectionPort
interface IGetAllRepositoryCollectionsPort

class MongoDBAdapter {
    - credentialModel: Model<GitCredentialDocument>
    - analysisModel: Model<GitHubAnalysisDocument>
    - docsReportModel: Model<DocumentationReportDocument>
    - codeReportModel: Model<CodeReportDocument>
    - securityReportModel: Model<SecurityReportDocument>
    - collectionModel: Model<GitHubCollectionDocument>
    ---
    + MongoDBAdapter(credentialModel, analysisModel, docsReportModel, codeReportModel, securityReportModel, collectionModel)
    + authorize(model): Promise<GetGitCredentialResponse>
    + save(request): Promise<PostGitCredentialResponse>
    + deletePAT(request): Promise<DeleteGitCredentialResponse>
    + updatePAT(request): Promise<UpdateGitCredentialPatResponse>
    + saveAnalysis(request): Promise<SaveGitHubAnalysisResponse>
    + saveDocsReport(request): Promise<SaveDocsReportResponse>
    + saveSecurityReport(request): Promise<SaveSecurityReportResponse>
    + updateAnalysis(request): Promise<AddReportsToAnalysisResult>
    + getAnalysisFromId(id): Promise<GitHubAnalysisDetailedResult>
    + getAllAnalysesForUser(userId): Promise<GetAllAnalysesForUserResponse>
    + checkDuplicate(request): Promise<CheckCollectionDuplicateResponse>
    + addCollection(request): Promise<AddRepositoryCollectionResponse>
    + getCollection(request): Promise<GetRepositoryCollectionResponse>
    + getAllCollections(request): Promise<GetAllRepositoryCollectionsResponse>
}

MongoDBAdapter ..|> IGitCredentialReadPort
MongoDBAdapter ..|> IGitCredentialSavePort
MongoDBAdapter ..|> IGitCredentialDeletePort
MongoDBAdapter ..|> IGitCredentialUpdatePort
MongoDBAdapter ..|> IGitHubAnalysisSavePort
MongoDBAdapter ..|> IDocsReportSavePort
MongoDBAdapter ..|> ISecurityReportSavePort


MongoDBAdapter ..|> IUpdateAnalysisPort
MongoDBAdapter ..|> IGetAnalysisFromIdPort
MongoDBAdapter ..|> IGetAllAnalysesForUserPort
MongoDBAdapter ..|> ICollectionDuplicateCheckerPort
MongoDBAdapter ..|> ICollectionAdderPort
MongoDBAdapter ..|> IGetRepositoryCollectionPort
MongoDBAdapter ..|> IGetAllRepositoryCollectionsPort
@enduml