@startuml S3Adapter
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface IGitClonePort {
    + clone(request: CloneRepoRequest): Promise<CloneRepoResponse>
}

class S3Adapter {
    - s3Client: S3Client
    - logger: Logger
    - configService: ConfigurationService
    ---
    + S3Adapter(configService: ConfigurationService)
    - extractRepoPath(repositoryUrl: string): string
    + clone(request: CloneRepoRequest): Promise<CloneRepoResponse>
}

S3Adapter ..|> IGitClonePort
@enduml