@startuml GitHubAnalysis
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GitHubAnalysis {
    - analysisId: AnalysisId
    - userId: UserId
    - repoURL: RepoURL
    - branch: BranchName
    - commit: CommitHash
    - codeReportId: ReportId | null
    - docsReportId: ReportId | null
    - securityReportId: ReportId | null
    - status: AnalysisStatus
    ---
    - GitHubAnalysis(id, user, url, branch, commit, codeReportId, docsReportId, securityReportId)
    + {static} create(properties: GitHubAnalysisProps): GitHubAnalysis
    + getAnalysisId(): AnalysisId
    + getUserId(): UserId
    + getRepoURL(): RepoURL
    + getBranch(): BranchName
    + getCommit(): CommitHash
    + getCodeReportId(): ReportId | null
    + getDocsReportId(): ReportId | null
    + getSecurityReportId(): ReportId | null
    + getStatus(): AnalysisStatus
    + inProgress(): void
    + complete(): void
    + failed(): void
    + pending(): void
    + equals(other: GitHubAnalysis): boolean
}

GitHubAnalysis --right-> AnalysisId
GitHubAnalysis --right-> UserId
GitHubAnalysis --left-> ReportId
GitHubAnalysis --left-> RepoURL
GitHubAnalysis --down-> BranchName
GitHubAnalysis --down-> CommitHash
GitHubAnalysis --down-> AnalysisStatus
@enduml