@startuml GitHubAnalysis
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GitHubAnalysis {
    - analysisId: AnalysisId
    - userId: UserId
    - repoURL: RepoURL
    - branch: BranchName
    - commit: CommitHash
    - status: AnalysisStatus
    ---
    - GitHubAnalysis(id, user, url, branch, commit)
    + {static} create(properties: GitHubAnalysisProps): GitHubAnalysis
    + getRepoURL(): RepoURL
    + getBranch(): BranchName
    + getCommit(): CommitHash
    + getAnalysisId(): AnalysisId
    + inProgress(): void
    + complete(): void
    + failed(): void
    + equals(other: GitHubAnalysis): boolean
}

GitHubAnalysis --right-> AnalysisId
GitHubAnalysis --right-> UserId
GitHubAnalysis --down-> RepoURL
GitHubAnalysis --down-> BranchName
GitHubAnalysis --down-> CommitHash
GitHubAnalysis --left-> AnalysisStatus
@enduml