@startuml UpdatePatRequestDTO
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class UpdatePatRequestDTO {
    + repositoryUrl: string
    + password: string
    + newPersonalAccessToken: string
    ---
    + UpdatePatRequestDTO(repositoryUrl, password, newPersonalAccessToken)
}
@enduml