@startuml ICodeReportSavePort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface ICodeReportSavePort {
    + saveCodeReport(model: SaveCodeReportRequest): Promise<SaveCodeReportResponse>
}

ICodeReportSavePort --down-> SaveCodeReportRequest
ICodeReportSavePort --down-> SaveCodeReportResponse
@enduml