@startuml ICollectionDuplicateCheckerPort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface ICollectionDuplicateCheckerPort {
    + checkDuplicate(model: CheckCollectionDuplicateRequest): Promise<CheckCollectionDuplicateResponse>
}

ICollectionDuplicateCheckerPort --right-> CheckCollectionDuplicateRequest
ICollectionDuplicateCheckerPort --right-> CheckCollectionDuplicateResponse
@enduml