@startuml IDocumentationAgentPort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class IDocumentationAgentPort <<Interface>> {
    + runAnalysis(model: AgentRequest): Promise<DocsAgentResponse>
}

IDocumentationAgentPort --down.> AgentRequest
IDocumentationAgentPort --down.> DocsAgentResponse
@enduml