@startuml IGetAllRepositoryCollectionsPort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface IGetAllRepositoryCollectionsPort {
    + getAllCollections(model: GetAllRepositoryCollectionsRequest): Promise<GetAllRepositoryCollectionsResponse>
}

IGetAllRepositoryCollectionsPort --down.> GetAllRepositoryCollectionsRequest
IGetAllRepositoryCollectionsPort --down.> GetAllRepositoryCollectionsResponse
@enduml