@startuml IGetRepositoryCollectionPort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class IGetRepositoryCollectionPort <<Interface>> {
    + getRepositoryCollection(model: GetRepositoryCollectionRequest): Promise<GetRepositoryCollectionResponse>
}

IGetRepositoryCollectionPort --down.> GetRepositoryCollectionRequest
IGetRepositoryCollectionPort --down.> GetRepositoryCollectionResponse
@enduml