@startuml IGitCredentialReadPort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface IGitCredentialReadPort {
    + authorize(model: GetGitCredentialRequest): Promise<GetGitCredentialResponse>
}

IGitCredentialReadPort --down-> GetGitCredentialRequest
IGitCredentialReadPort --down-> GetGitCredentialResponse
@enduml