@startuml ISecurityAgentPort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface ISecurityAgentPort {
    + runAnalysis(model: AgentRequest): Promise<SecAgentResponse>
}

ISecurityAgentPort --right-> AgentRequest
ISecurityAgentPort --right-> SecAgentResponse
@enduml