@startuml IUpdateAnalysisPort
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface IUpdateAnalysisPort {
    + addReportsToAnalysis(model: AddReportsToAnalysisRequest): Promise<AddReportsToAnalysisResult>
}

IUpdateAnalysisPort --down.> AddReportsToAnalysisRequest
IUpdateAnalysisPort --down.> AddReportsToAnalysisResult
@enduml