@startuml Email

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class Email {
    - _value: string
    ---
    - Email(value: string)
    + {static} create(value: string): Email
    - validate(value: string): string
    + equals(other: Email): boolean
    + get value(): string
}

@enduml
