@startuml DeleteGitCredentialRequest
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class DeleteGitCredentialRequest {
    + repoUrl: RepoURL
    + patPassword: PATPassword
    ---
    + DeleteGitCredentialRequest(repoUrl, patPassword)
}

DeleteGitCredentialRequest --right-> RepoURL
DeleteGitCredentialRequest --right-> PATPassword
@enduml