@startuml GetAllRepositoryCollectionsRequest
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GetAllRepositoryCollectionsRequest {
    + user: UserId
    ---
    + GetAllRepositoryCollectionsRequest(user: UserId)
}

GetAllRepositoryCollectionsRequest --right-> UserId
@enduml