@startuml GetGitCredentialRequest
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GetGitCredentialRequest {
    + repoUrl: RepoURL
    + password: PATPassword
    ---
    + GetGitCredentialRequest(repoUrl, password)
}

GetGitCredentialRequest --right-> RepoURL
GetGitCredentialRequest --right-> PATPassword
@enduml