@startuml PostGitCredentialRequest
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class PostGitCredentialRequest {
    + repoUrl: RepoURL
    + password: PATPassword
    + pat: PersonalAccessToken
    ---
    + PostGitCredentialRequest(repoUrl, password, pat)
}

PostGitCredentialRequest --right-> RepoURL
PostGitCredentialRequest --right-> PATPassword
PostGitCredentialRequest --down-> PersonalAccessToken
@enduml