@startuml UpdateGitCredentialPatRequest
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class UpdateGitCredentialPatRequest {
    + repoUrl: RepoURL
    + patPassword: PATPassword
    + newPat: PersonalAccessToken
    ---
    + UpdateGitCredentialPatRequest(repoUrl, patPassword, newPat)
}

UpdateGitCredentialPatRequest --right-> RepoURL
UpdateGitCredentialPatRequest --right-> PATPassword
UpdateGitCredentialPatRequest --down-> PersonalAccessToken
@enduml