@startuml DescriptionFinding

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class DescriptionFinding {
    - descriptionFinding: string
    ---
    - DescriptionFinding(descriptionFinding: string)
    + getDescriptionFinding() : string
    + {static} create(descriptionFinding: string) : DescriptionFinding
}

@enduml