@startuml FileCoverage
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class FileCoverage {
    - _pathFinding: PathFinding
    - _linesPercentage: CoveragePercentage
    - _branchesPercentage: CoveragePercentage
    - _missedLines: number[]
    ---
    - FileCoverage(path, lines, branches, missed)
    - validate(): void
    + {static} create(path, lines, branches, missed): FileCoverage
    + getPath(): PathFinding
    + getLinesPercentage(): CoveragePercentage
    + getBranchesPercentage(): CoveragePercentage
    + getMissedLines(): number[]
    + equals(other: FileCoverage): boolean
}

FileCoverage --right-> PathFinding
FileCoverage --right-> CoveragePercentage
@enduml