@startuml MissingInConfigDependency
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class MissingInConfigDependency {
    - _name: string
    - _pathFinding: PathFinding
    - _severity: SeverityFinding
    ---
    - MissingInConfigDependency(name, pathFinding, severity)
    + {static} create(name: string, pathFinding: PathFinding, severity: SeverityFinding): MissingInConfigDependency
    + getName(): string
    + getPathFinding(): PathFinding
    + getSeverityFinding(): SeverityFinding
    + equals(other: MissingInConfigDependency): boolean
}

MissingInConfigDependency --right-> PathFinding
MissingInConfigDependency --left-> SeverityFinding
@enduml