@startuml OWASPFinding
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class OWASPFinding {
    - _pathFinding: PathFinding
    - _errorFinding: ErrorFinding
    - _owaspCategory: string
    ---
    - OWASPFinding(path, error, category)
    + {static} create(pathFinding, errorFinding, owaspCategory): OWASPFinding
    + getPathFinding(): PathFinding
    + getErrorFinding(): ErrorFinding
    + getOWASPCategory(): string
    + equals(other: OWASPFinding): boolean
}

OWASPFinding --down-> PathFinding
OWASPFinding --down-> ErrorFinding
@enduml