@startuml PathFinding

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class PathFinding {
    - pathFinding: string
    ---
    - PathFinding(path: string)
    + getPathFinding() : string
    + {static} create(path: string) : PathFinding
}

@enduml