@startuml RepoURL

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class RepoURL {
    - _value: string
    ---
    - RepoURL(value: string)
    - validate(value: string): void
    + equals(other: RepoURL): boolean
    + getValue(): string
    + {static} create(value: string): RepoURL
}

@enduml