@startuml SecretFinding
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class SecretFinding {
    - _pathFinding: PathFinding
    - _errorFinding: ErrorFinding
    - _secretCategory: string
    ---
    - SecretFinding(path, error, category)
    + {static} create(pathFinding, errorFinding, secretCategory): SecretFinding
    + getPathFinding(): PathFinding
    + getErrorFinding(): ErrorFinding
    + getSecretCategory(): string
    + equals(other: SecretFinding): boolean
}

SecretFinding --right-> PathFinding
SecretFinding --right-> ErrorFinding
@enduml