@startuml SeverityFinding

skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

class SeverityFinding {
    - severityFinding: string
    ---
    - SeverityFinding(severity: string)
    + getSeverity() : string
    + {static} create(severity: string) : SeverityFinding
}

@enduml