@startuml StaticAnalysisFinding
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

enum SupportedLanguages {
    PYTHON
    JAVASCRIPT
    TYPESCRIPT
    JAVA
}

class StaticAnalysisFinding {
    - _path: PathFinding
    - _errorCategory: string
    - _errorFinding: ErrorFinding
    - _analyzedLanguage: SupportedLanguages
    ---
    - StaticAnalysisFinding(path, category, error, language)
    - validate(language): void
    + {static} create(path, category, error, language): StaticAnalysisFinding
    + getPathFinding(): PathFinding
    + getErrorCategory(): string
    + getErrorFinding(): ErrorFinding
    + getAnalyzedLanguage(): SupportedLanguages
}

StaticAnalysisFinding --right-> PathFinding
StaticAnalysisFinding --right-> ErrorFinding
StaticAnalysisFinding --down-> SupportedLanguages
@enduml