@startuml DeleteRepositoryCollectionResponseDTO
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 50
skinparam ClassAttributeIconSize 0
hide circles

class DeleteRepositoryCollectionResponseDTO {
    + deleted: boolean
    + message?: string
    ---
    - DeleteRepositoryCollectionResponseDTO(deleted, message?)
    + {static} success(): DeleteRepositoryCollectionResponseDTO
    + {static} failure(err: string): DeleteRepositoryCollectionResponseDTO
}

@enduml