@startuml GetAnalysisResponseDTO
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 50
skinparam ClassAttributeIconSize 0
hide circles

class GetAnalysisResponseDTO {
    + success: boolean
    + message?: string
    + analysisId?: string
    + userId?: string
    + repoURL?: string
    + branch?: string
    + commit?: string
    + status?: string
    + createdAt?: string
    + updatedAt?: string
    + docsReportJson?: DocsAnalysisReportDTO | null
    + codeReportJson?: CodeAnalysisReportDTO | null
    + secReportJson?: SecAnalysisReportDTO | null
    ---
    + GetAnalysisResponseDTO(success, message?, analysisId?, userId?, repoURL?, branch?, commit?, 
    status?, createdAt?, updatedAt?, docsReportJson?, codeReportJson?, secReportJson?)
    + {static} fromResult(result: GetAnalysisResult): GetAnalysisResponseDTO
}

GetAnalysisResponseDTO --> DocsAnalysisReportDTO
GetAnalysisResponseDTO --> CodeAnalysisReportDTO
GetAnalysisResponseDTO --> SecAnalysisReportDTO
GetAnalysisResponseDTO ..> GetAnalysisResult

@enduml