@startuml ICodeReportEntityProvider
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface ICodeReportEntityProvider {
    + fromCodeAgentResponse(response: CodeAgentResponse, reportId: ReportId, analysisId: AnalysisId): CodeAgentReport
}

ICodeReportEntityProvider --down-> CodeAgentReport
@enduml