@startuml IPasswordProvider
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface IPasswordProvider {
    + generate(password: string): PATPassword
}

IPasswordProvider --right-> PATPassword
@enduml