@startuml PATPasswordProvider
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class IPasswordProvider <<Interface>> {
    + generate(password: string): PATPassword
}

class PATPasswordProvider {
    ---
    + generate(password: string): PATPassword
}

PATPasswordProvider ..|> IPasswordProvider
PATPasswordProvider --right-> PATPassword
@enduml