@startuml Clone
skinparam linetype ortho
skinparam nodesep auto
skinparam ranksep 70
skinparam ClassAttributeIconSize 0

skinparam PackageBorderColor white
skinparam PackageStyle Rectangle
skinparam PackageFontColor white
hide circles


title Diagramma Integrale - CodeGuardian Analysis Microservice

skinparam class {
    BackgroundColor White
    BorderColor #555555
    ArrowColor #555555
    FontSize 11
}

skinparam package {
    BorderColor white
    Style Rectangle
    PackageFontColor white
}

skinparam interface {
    BackgroundColor #E8F5E9
    BorderColor #2E7D32
    FontSize 12
}

package DTO {
    class AnalysisRequestDTO <<Request DTO>> {
        + repoURL: string
        + branch?: string
        + password?: string
        + commit?: string
        //Da aggiungere i componenti della\n  richiesta
    }

    class AnalysisResponseDTO <<Response DTO>> {
        + analysisId: string
        + status: string
        + requestedAt: Date
        + estimatedTime?: Time

        + AnalysisResponseDTO(id: string, status: string, date: Date, time?: Time)
    }

    class AnalysisDTO <<Response DTO>> {
        + analysisId: string
        + userID: string
        + repoURL: string
        + branch: string
        + commit?: string
        + status: string
        + requestedAt: Date
        + completedAt?: Date
        //Da aggiungere tutti i vari errori, i risultati e le metriche
        + AnalysisDTO(id: string, userID: string, repoURL: string, branch: string, commit: string, status: string, requestedAt: Date, completedAt?: Date)
    }

    class DataBaseUserDTO <<Request DTO>> {
        + userID: string
        + repoURL: string
        + password?: string

        + DataBaseUserDTO(userID: string, repoURL: string, password?: string)
    }

    class DataBaseIDDTO <<Request DTO>> {
        + analysisID: string
        + repoURL: string
        + password?: string

        + DataBaseIDDTO(analysisID: string, repoURL: string, password?: string)
    }
}

package Controllers {
    class AnalysisController {
        - startAnalysisUseCase: IStartAnalysisUseCase
        + requestAnalysis(userID: string, repoInfo: AnalysisRequestDTO): Promise<AnalysisResponseDTO>
    }

    class DataBaseController {
        - getByUserUseCase: IGetAnalysisByUserUseCase
        - getByIDUseCase: IGetAnalysisByIDUseCase
        + getReportsByUser(command: DataBaseUserDTO): Promise<AnalysisDTO[]>
        + getReportByID(command: DataBaseIDDTO): Promise<AnalysisDTO>
    }
}

package Commands {
    class StartAnalysisCommand <<Command>> {
        + userID: string
        + repoURL: string
        + branch: string ?? 'main'
        + password?: string
        + commit?: string

        + StartAnalysisCommand(userID: string, repoURL: string, branch?: string, password?: string, commit?: string)
    }

    class DataBaseIDCommand <<Command>> {
        + analysisID: string
        + repoURL: string
        + password?: string

        + DataBaseIDCommand(analysisID: string)
    }

    class DataBaseUserCommand <<Command>> {
        + userID: string

        + DataBaseUserCommand(userID: string)
    }
}

package UseCases {
    interface IStartAnalysisUseCase <<Inbound Port>> {
        + {abstract} start(command: StartAnalysisCommand): Promise<AnalysisResponseDTO>
    }

    interface IGetAnalysisByUserUseCase <<Inbound Port>> {
        + {abstract} getByUser(userID: string): Promise<AnalysisDTO[]>
    }

    interface IGetAnalysisByIDUseCase <<Inbound Port>> {
        + {abstract} getByIdUseCase(command: DataBaseIDCommand): Promise<AnalysisDTO>
    }

}

package Application {
    class StartAnalysisService {
        - repository: IAnalysisRepository
        - credentialManager: ICredentialAnalysisPort
        - gitValidator: IGitValidatorPort
        - gitCloner: IGitClonerPort
        - orchestator: IAnalysisOrchestratorPort
        - saveAnalysis(analysis: Analysis): Promise<void>
        - retrievePersonalAccessToken(credentials: Credentials): Promise<string>
        - verifyRepositoryExistance(repository: GitRequest): Promise<GitCheckResult>
        - cloneRepository(cloneRepository: GitCloneRequest): Promise<string>
        - persistToCloudStorage(source: LocalRepository) : Promise<string>
        - startExternalOrchestration(task: AnalysisStartTask) : Promise<void>
        + StartAnalysisService(repository: IAnalysisRepository)
        + start(command: StartAnalysisCommand): Promise<AnalysisResponseDTO>
    }

    class DatabaseService {
        - MongoByUser: IMongoGetByUser
        - MongoByID: IMongoGetByID
        - CredentialsManager: ICredentialDbPort
        - getPersonalAccessToRepository(credentials: Credentials): Promise<bool>
        + DatabaseService()
        + getReportsByUser(command: DataBaseUserCommand): Promise<AnalysisDTO[]>
        + getReportByID(command: DataBaseIDCommand): Promise<AnalysisDTO>
    }
}

class Analysis <<Entity>> {
    - analysisID: AnalysisId
    - status: enum
    - userID: UserId

    - Analysis(id: AnalysisId, userID: UserId, status: enum)
    + {static} create(id: AnalysisId, userID: UserId, status: enum): Analysis
    + getAnalysisID(): AnalysisId
    + getStatus(): enum
    + getUserID(): UserId
    + setStatus(status: enum): void
}

class GitHubAnalysis <<Entity>> {
    - repoURL: RepoUrl
    - branch: Branch
    - commit?: CommitHash

    - GitHubAnalysis(id: AnalysisId, userID: UserId, repoURL: RepoUrl, branch: Branch, commit?: CommitHash)
    + {static} create(id: AnalysisId, userID: UserId, repoURL: RepoUrl, branch: Branch, commit?: CommitHash): GitHubAnalysis
    + getRepoURL(): RepoUrl
    + getBranch(): Branch
    + getCommit(): CommitHash | null
}

class RepoURL <<Value Object>> {
    - url: string

    - RepoURL(url: string)
    + {static} create(url: string): RepoURL
    + getURL(): string
}

enum AnalysisStatus {
    INITIALIZING
    PENDING
    RUNNING
    COMPLETED
    FAILED
}

class Credentials <<Entity>> {
    - repoURL: RepoURL
    - password: PATPassword

    - Credentials(repoURL: RepoURL, password: PATPassword)
    + {static} create(repoURL: RepoURL, password: PATPassword): Credentials
    + getRepoURL(): RepoURL
    + getPassword(): PATPassword
}

class GitRequest <<Entity>> {
    - repoURL: RepoURL
    - pat?: PersonalAccessToken

    - GitRequest(repoURL: RepoURL, pat?: PersonalAccessToken)
    + {static} create(repoURL: RepoURL, pat?: PersonalAccessToken): GitRequest
    + getRepoURL(): RepoURL
    + getPersonalAccessToken(): PersonalAccessToken | null
}

enum GitCheckResult {
    EXISTS
    NOT_FOUND
    UNAUTHORIZED
    FORBIDDEN
    UNAVAILABLE
}

class GitCloneRequest <<Value Object>> {
    - analysisID: string
    - repoURL: RepoURL
    - branch: Branch
    - pat: PersonalAccessToken | null
    - commit: CommitHash | null

    - GitCloneRequest(id: string, url: string, branch: Branch, pat?: PersonalAccessToken, commit?: CommitHash)
    + {static} create(id: string, url: string, branch: Branch, pat?: PersonalAccessToken, commit?: CommitHash) : GitCloneRequest
    
    + getAnalysisID() : AnalysisId
    + getRepoURL() : RepoURL
    + getBranch() : Branch
    + getPat() : PersonalAccessToken | null
    + getCommit() : CommitHash | null
}

class LocalRepository <<Value Object>> {
    - fullPath: string
    - analysisId: AnalysisId

    - LocalRepository(path: string, id: AnalysisId)
    + {static} create(path: string, id: AnalysisId) : LocalRepository
    + getFullPath() : string
    + getAnalysisID() : AnalysisId
}

class PersonalAccessToken <<Value Object>> {
    - token: string

    - PersonalAccessToken(token: string)
    + {static} create(token: string) : PersonalAccessToken
    + getToken() : string
}


class AnalysisStartTask <<Value Object>> {
    - analysisID: AnalysisId
    - storageLocation: S3Location
    - AnalysisStartTask(id: AnalysisId, location: S3Location)
    + {static} create(id: AnalysisId, location: S3Location) : AnalysisStartTask
    + getAnalysisID() : AnalysisId
    + getStorageLocation() : S3Location
}

class S3Location <<Value Object>> {
    - uri: string

    - S3Location(uri: string)
    + {static} create(uri: string) : S3Location
    + getURI() : string
}

class UserID <<Value Object>> {
    - userID: string

    - UserID(userID: string)
    + {static} create(userID: string) : UserID
    + getUserID() : string
}

class AnalysisId <<Value Object>> {
    - analysisId: string

    - AnalysisId(analysisId: string)
    + {static} create(analysisId: string) : AnalysisId
    + getAnalysisId() : string
}

class Branch <<Value Object>> {
    - branch: string

    - Branch(branch: string)
    + {static} create(branch: string) : Branch
    + getBranch() : string
}

class CommitHash <<Value Object>> {
    - commit: string

    - CommitHash(commit: string)
    + {static} create(commit: string) : CommitHash
    + getCommit() : string
}

class PATPassword <<Value Object>> {
    - password: string

    - PATPassword(password: string)
    + {static} create(password: string) : PATPassword
    + getPassword() : string
}


package Ports {
    interface ICredentialAnalysisPort <<Outbound Port>> {
        + {abstract} getPersonalAccessToken(credentials: Credentials): Promise<string>
    }
    
    interface IAnalysisRepository <<Outbound Port>> {
        + {abstract} save(analysis: Analysis): Promise<void>
    }

    interface IGitValidatorPort <<Outbound Port>> {
        + {abstract} checkRepositoryExistance(repository: GitRequest): Promise<GitCheckResult>
    }

    interface IGitClonerPort <<Outbound Port>> {
        + {abstract} cloneRepository(request: GitCloneRequest): Promise<string> 
    }

    interface IStoragePort <<Outbound Port>> {
        + {abstract} uploadToStorage(source: LocalRepository) : Promise<string>
    }

    interface IAnalysisOrchestratorPort <<Outbound Port>> {
        + {abstract} triggerAnalysis(task: AnalysisStartTask) : Promise<void>
    }

    interface IMongoGetByUser <<Outbound Port>> {
        + {abstract} getReportsByUser(userID: UserID): Promise<Analysis[]>
    }

    interface IMongoGetByID <<Outbound Port>> {
        + {abstract} getReportByID(analysisID: AnalysisID): Promise<Analysis>
    }

    interface ICredentialDbPort <<Outbound Port>> {
        + {abstract} getPersonalAccessToRepository(credentials: Credentials): Promise<bool>
    }
}

package Adapters {
    class MongoDBAdapter {
        + save(analysis: Analysis): Promise<void>
        + getReportsByUser(userID: UserID): Promise<Analysis[]>
        + getReportByID(analysisID: AnalysisID): Promise<Analysis>
    }

    class CredentialsMicroserviceAdapter {
        + getPersonalAccessToken(credentials: Credentials): Promise<string>
        + getPersonalAccessToRepository(credentials: Credentials): Promise<bool>
    }

    class GitHubAdapter {
        + checkRepositoryExistance(repository: GitRequest): Promise<GitCheckResult>
        + cloneRepository(request: GitCloneRequest): Promise<string>
    }

    class S3Adapter {
        + uploadToStorage(source: LocalRepository) : Promise<string>
    }

    class StepFunctionAdapter {
        + triggerAnalysis(task: AnalysisStartTask) : Promise<void>
    }
}

' --- RELATIONS ---
AnalysisController ..up-> AnalysisRequestDTO: "receives"
AnalysisController -down-> IStartAnalysisUseCase: "invokes"
AnalysisController ..down-> StartAnalysisCommand: "creates"
AnalysisController ..up-> AnalysisResponseDTO: "responses"

DataBaseController ..up-> DataBaseUserDTO: "receives"
DataBaseController ..up-> DataBaseIDDTO: "receives"
DataBaseController -down-> IGetAnalysisByUserUseCase: "invokes"
DataBaseController -down-> IGetAnalysisByIDUseCase: "invokes"
DataBaseController ..down-> DataBaseUserCommand: "creates"
DataBaseController ..down-> DataBaseIDCommand: "creates"
DataBaseController ..up-> AnalysisDTO: "responses"

IStartAnalysisUseCase ..up-> StartAnalysisCommand: "uses"

StartAnalysisService ..up.|> IStartAnalysisUseCase 
StartAnalysisService --down-> IAnalysisRepository
StartAnalysisService --down-> ICredentialAnalysisPort
StartAnalysisService --down-> IGitValidatorPort
StartAnalysisService --down-> IGitClonerPort
StartAnalysisService --down-> IStoragePort
StartAnalysisService --down-> IAnalysisOrchestratorPort

IGetAnalysisByIDUseCase ..up-> DataBaseIDCommand : "uses"
IGetAnalysisByUserUseCase ..up-> DataBaseUserCommand : "uses"

DatabaseService ..up.|> IGetAnalysisByUserUseCase 
DatabaseService ..up.|> IGetAnalysisByIDUseCase 
DatabaseService --down-> IMongoGetByUser
DatabaseService --down-> IMongoGetByID
DatabaseService --down-> ICredentialDbPort

StartAnalysisService ..down-> Analysis
StartAnalysisService ..down-> Credentials
StartAnalysisService ..down-> GitRequest
StartAnalysisService ..down-> GitCheckResult
StartAnalysisService ..down-> GitCloneRequest
StartAnalysisService ..down-> LocalRepository
StartAnalysisService ..down-> AnalysisStartTask

DatabaseService ..down-> Credentials
DatabaseService ..down-> Analysis
DatabaseService ..down-> UserID
DatabaseService ..down-> AnalysisId

Analysis --left-> AnalysisStatus

ICredentialAnalysisPort ..up-> Credentials
ICredentialDbPort ..up-> Credentials
IMongoGetByID ..up-> AnalysisId
IMongoGetByUser ..up-> UserID

IAnalysisRepository ..up-> Analysis
IMongoGetByUser ..up.> Analysis
IMongoGetByID ..up.> Analysis

IGitValidatorPort ..up-> GitRequest
IGitValidatorPort ..up-> GitCheckResult

IGitClonerPort ..up-> GitCloneRequest

IStoragePort ..up-> LocalRepository

IAnalysisOrchestratorPort ..up-> AnalysisStartTask


MongoDBAdapter ..up-|> IAnalysisRepository

CredentialsMicroserviceAdapter ..up-|> ICredentialAnalysisPort
CredentialsMicroserviceAdapter ..up-|> ICredentialDbPort

GitHubAdapter ..up-|> IGitValidatorPort
GitHubAdapter ..up-|> IGitClonerPort

S3Adapter ..up-|> IStoragePort

StepFunctionAdapter ..up-|> IAnalysisOrchestratorPort

MongoDBAdapter ..down-|> IMongoGetByUser
MongoDBAdapter ..down-|> IMongoGetByID


'relazioni tra entity e value object
Analysis *--down-> AnalysisId
Analysis *--left-> UserID
GitHubAnalysis ..up.|> Analysis
GitHubAnalysis *--right-> RepoURL
GitHubAnalysis *--left-> Branch
GitHubAnalysis *--right-> CommitHash

Credentials *--left-> RepoURL
Credentials *--right-> PATPassword

AnalysisStartTask *--left-> AnalysisId
AnalysisStartTask *--right-> S3Location

GitRequest *--right-> RepoURL

GitCloneRequest *--left-> AnalysisId
GitCloneRequest *--left-> RepoURL
GitCloneRequest *--right-> PersonalAccessToken
GitCloneRequest *--right-> Branch
GitCloneRequest *--right-> CommitHash

GitRequest *--up-> PersonalAccessToken

LocalRepository *--left-> AnalysisId
@enduml