@startuml Clone

skinparam linetype ortho
skinparam nodesep 70
skinparam ranksep 70
skinparam ClassAttributeIconSize 0
hide circles

title Diagramma Integrale - CodeGuardian Analysis Microservice

skinparam class {
    BackgroundColor White
    BorderColor #555555
    ArrowColor #555555
    FontSize 12
}

skinparam interface {
    BackgroundColor #E8F5E9
    BorderColor #2E7D32
    FontSize 12
}

class StartAnalysisDTO <<DTO>> {
    + repoURL: string
    + branch: string ?? "main"
    + password? : string
    + shaCommit: string ?? ""
}

class AnalysisResponse {
    + analysisId: string
    + status: string
    + repoURL: string
    + branch: string
    + requestedAt: Date
}

class AnalysisRequest <<ValueObject>> {
    + userID: string
    + repoURL: string
    + branch: string 
    + password? : string  
    + commit?: string
}

class PersonalAccessTokenDTO <<DTO>> {
    + pat: string | undefined
}

class RepositoryRequest {
    repoURL: string
    branch: string ?? "main"
    commit: string | undefined
    pat: string | undefined
}

class RepoCheckResult {
    + resultCode: HTTPStatusCode
}

' --- CONTROLLER ---
package Controller <<Rectangle>> #FFFFFF {

    class AnalysisController {
        - analysisUseCase: IAnalysisUseCase
        + startAnalysis(userID: string, analysisDTO: StartAnalysisDTO) : AnalysisResponse
    }

    note left of AnalysisController::startAnalysis
    async startAnalysis(
        @Headers('x-user-id') userId: string,
        @Body() dto: StartAnalysisDTO
    ) { ... }
    // Body passato dal Client, Header passato dal JWT
    end note

    note right of AnalysisController::startAnalysis
        const request = new AnalysisRequest(...)
    end note

    class ReportController {
        - dbUseCase: IDBUseCase
    }

}

interface IAnalysisUseCase <<Interface>> {
    + {abstract} executeAnalysis(analysisRequest: AnalysisRequest) : Promise<AnalysisResponse>
}

interface IDBUseCase <<Interface>> {}

class AnalysisService {
    - credentialManagerPort: ICredentialManagerPort
    - dbUseCase: IDBUseCase
    - sourceControlPort: ISourceControlPort
    - createRepositoryRequest(analysisRequest: AnalysisRequest) : RepositoryRequest
    + executeAnalysis(analysisRequest: AnalysisRequest) : Promise<AnalysisResponse>
}

note left of AnalysisService::createRepositoryRequest
    let pat : string | undefined
    if(analysisRequest.password) {
        const credentials = await this.ICredentialManagerPort.retrievePersonalAccessToken(analysisRequest.repoURL, analysisRequest.password)
        pat = credentials.pat
    }
    return RepositoryRequest(analysisRequest.repoURL, analysisRequest.branch, analysisRequest.commit, pat)
end note

class DBService {
    + memorizeSecurityReport()
    + memorizeOWASPReport()
}

interface ISourceControlPort <<Interface>> {
    + {abstract} checkRepositoryExists(repositoryRequest: RepositoryRequest) : Promise<RepoCheckResult>
    + {abstract} clone(repoUrl: string, localPath: string): Promise<void>
}

interface ICredentialManagerPort <<Interface>> {
    + {abstract} retrievePersonalAccessToken(repoURL: string, password: string) : Promise<PersonalAccessTokenDTO>
}

interface IPersistenceRepository <<Interface>> {}


class GitHubAdapter {
    + checkRepositoryExists(repositoryRequest: RepositoryRequest) : Promise<RepoCheckResult>
    + clone(repoUrl: string, localPath: string): Promise<void>
}

note left of GitHubAdapter
curl -H "Authorization: Bearer IL_TUO_TOKEN (se presente)" 
        -H "Accept: application/vnd.github.sha"      
        https://api.github.com/repos/OWNER/REPO/commits/BRANCH
end note

class MongoDBAdapter {}

class CredentialMicroserviceAdapter {
+ retrievePersonalAccessToken(repoURL: string, password: string) : Promise<PersonalAccessTokenDTO>  
}


' --- RELAZIONI ---
AnalysisController --down-> IAnalysisUseCase
AnalysisController ..left-> StartAnalysisDTO
AnalysisController ..left-> AnalysisResponse : "returns"
AnalysisController ..down-> AnalysisRequest : "istantiate"

ReportController --down-> IDBUseCase

IAnalysisUseCase ..up-> AnalysisRequest

DBService --up|> IDBUseCase

AnalysisService ..up|> IAnalysisUseCase
AnalysisService --down-> ISourceControlPort
AnalysisService --down-> ICredentialManagerPort
AnalysisService --down-> IDBUseCase
AnalysisService ..right-> RepositoryRequest

DBService --down-> IPersistenceRepository

ISourceControlPort ..left-> RepoCheckResult
ICredentialManagerPort ..right-> PersonalAccessTokenDTO

GitHubAdapter ..up|> ISourceControlPort

MongoDBAdapter ..up|> IPersistenceRepository

CredentialMicroserviceAdapter ..up|> ICredentialManagerPort