@startuml perCardin
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50
skinparam ClassAttributeIconSize 0
hide circles

class DocumentationAnalysisAdapter
class LocalCodeAnalysisAdapter
class LocalSecurityAnalysisAdapter
class ECSDocumentationAnalysisAdapter
class ECSCodeAnalysisAdapter
class ECSSecurityAnalysisAdapter
class IDocsReportSavePort <<interface>>
class ICodeReportSavePort <<interface>>
class ISecurityReportSavePort <<interface>>
class IUpdateAnalysisPort     <<interface>>

class IDocumentationAgentPort <<interface>>
class ICodeAgentPort <<interface>>
class ISecurityAgentPort <<interface>>
class AnalysisOrchestratorService
class IAnalysisOrchestrator <<interface>>


AnalysisOrchestratorService --up-> ICodeReportSavePort
AnalysisOrchestratorService ..up.|> IAnalysisOrchestrator
AnalysisOrchestratorService --> IDocumentationAgentPort
AnalysisOrchestratorService --> ICodeAgentPort
AnalysisOrchestratorService --> ISecurityAgentPort
AnalysisOrchestratorService --left-> IDocsReportSavePort
AnalysisOrchestratorService --up-> ISecurityReportSavePort
AnalysisOrchestratorService --right-> IUpdateAnalysisPort
DocumentationAnalysisAdapter ..up.|> IDocumentationAgentPort
LocalCodeAnalysisAdapter ..up.|> ICodeAgentPort
LocalSecurityAnalysisAdapter ..up.|> ISecurityAgentPort
ECSDocumentationAnalysisAdapter ..up.|> IDocumentationAgentPort
ECSCodeAnalysisAdapter  ..up.|> ICodeAgentPort
ECSSecurityAnalysisAdapter  ..up.|> ISecurityAgentPort

