@startuml AddRepositoryCollectionCommand
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class AddRepositoryCollectionCommand {
    + user: string
    + url: string
    + name: string
    + description?: string
    ---
    + AddRepositoryCollectionCommand(data)
}
@enduml