@startuml DeletePatCommand
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class DeletePatCommand {
    + repositoryUrl: string
    + patPassword: string
    ---
    + DeletePatCommand(data)
}
@enduml