@startuml DeleteRepositoryCollectionCommand
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class DeleteRepositoryCollectionCommand {
    + url: RepoURL
    + user: UserId
    ---
    + DeleteRepositoryCollectionCommand(data)
}

DeleteRepositoryCollectionCommand --right-> RepoURL
DeleteRepositoryCollectionCommand --right-> UserId
@enduml