@startuml UpdatePatCommand
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class UpdatePatCommand {
    + repositoryUrl: string
    + patPassword: string
    + newPat: string
    ---
    + UpdatePatCommand(data)
}
@enduml