@startuml StatusMissing
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

enum StatusMissing {
    NOT_FOUND
    POSSIBLY_RENAMED
    WRONG_PATH
}
@enduml