@startuml GetAllAnalysesForUserResponse
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GetAllAnalysesForUserResponse {
    + dto: GitHubAnalysisGeneralDataDTO[]
    ---
    + GetAllAnalysesForUserResponse(dto: GitHubAnalysisGeneralDataDTO[])
}
@enduml