@startuml GetGitCredentialResponse
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GetGitCredentialResponse {
    + patToken: string | null
    + isAuthorized: boolean
    + errorMessage?: string
    ---
    + GetGitCredentialResponse(patToken, isAuthorized, errorMessage?)
    + {static} success(pat): GetGitCredentialResponse
    + {static} failure(error): GetGitCredentialResponse
}
@enduml