@startuml GitHubAnalysisDetailedResult
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GitHubAnalysisDetailedResult {
    + generalData: GitHubAnalysisGeneralDataDTO
    + docsReport: DocsAnalysisReportDTO | null
    + codeReport: CodeAnalysisReportDTO | null
    + secReport: SecAnalysisReportDTO | null
    ---
    + GitHubAnalysisDetailedResult(record, docsReport?, codeReport?, secReport?)
}
@enduml