@startuml SaveCodeReportResponse
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class SaveCodeReportResponse {
    + isSuccess: boolean
    + errorMessage?: string
    ---
    - SaveCodeReportResponse(isSuccess, errorMessage?)
    + {static} success(): SaveCodeReportResponse
    + {static} failure(error: string): SaveCodeReportResponse
}
@enduml