@startuml SaveDocsReportResponse
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class SaveDocsReportResponse {
    + isSuccess: boolean
    + errorMessage?: string
    ---
    - SaveDocsReportResponse(isSuccess, errorMessage?)
    + {static} success(): SaveDocsReportResponse
    + {static} failure(error: string): SaveDocsReportResponse
}
@enduml