@startuml GetAnalysisService
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface GetAnalysisUseCase {
    + execute(command: GetAnalysisFromIdCommand): Promise<GetAnalysisResult>
}

interface GetAllAnalysesForUserUseCase {
    + getAllAnalysesForUser(command: GetAllAnalysesForUserCommand): Promise<GetAllAnalysesForUserResult>
}

class GetAnalysisService {
    - getAnalysisFromIdPort: IGetAnalysisFromIdPort
    - getAllAnalysesForUserPort: IGetAllAnalysesForUserPort
    ---
    + GetAnalysisService(getAnalysisFromIdPort, getAllAnalysesForUserPort)
    + execute(command: GetAnalysisFromIdCommand): Promise<GetAnalysisResult>
    + getAllAnalysesForUser(command: GetAllAnalysesForUserCommand): Promise<GetAllAnalysesForUserResult>
}

GetAnalysisService ..up|> GetAnalysisUseCase
GetAnalysisService ..down|> GetAllAnalysesForUserUseCase
GetAnalysisService --right-> IGetAnalysisFromIdPort
GetAnalysisService --left-> IGetAllAnalysesForUserPort
@enduml