@startuml GitClonerService
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface IRepositoryCloner {
    + clone(repoUrl, analysisId, patToken, branch, commit): Promise<string>
}

class GitClonerService {
    - cloningPort: IGitClonePort
    ---
    + GitClonerService(cloningPort)
    + clone(repoUrl: RepoURL, analysisId: AnalysisId, patToken: PersonalAccessToken | null, branch: BranchName | null, commit: CommitHash | null): Promise<string>
}

GitClonerService ..|> IRepositoryCloner
GitClonerService --down-> IGitClonePort
@enduml