@startuml GitHubCollectionDeleter
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface DeleteRepositoryCollectionUseCase {
    + execute(command: DeleteRepositoryCollectionCommand): Promise<DeleteRepositoryCollectionResult>
}

class GitHubCollectionDeleter {
    - port: IDeleteRepositoryCollectionPort
    ---
    + GitHubCollectionDeleter(port)
    + execute(command: DeleteRepositoryCollectionCommand): Promise<DeleteRepositoryCollectionResult>
}

GitHubCollectionDeleter ..|> DeleteRepositoryCollectionUseCase
GitHubCollectionDeleter --right-> IDeleteRepositoryCollectionPort
@enduml