@startuml GitHubCollectionChecker
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface ICollectionExistenceChecker {
    + check(user: UserId, url: RepoURL): Promise<boolean>
}

interface ICollectionDuplicateCheckerPort

class GitHubCollectionChecker {
    - duplicateCheckerPort: ICollectionDuplicateCheckerPort
    ---
    + GitHubCollectionChecker(duplicateCheckerPort)
    + check(user: UserId, url: RepoURL): Promise<boolean>
}

GitHubCollectionChecker ..up.|> ICollectionExistenceChecker
GitHubCollectionChecker --down-> ICollectionDuplicateCheckerPort 

@enduml