@startuml GitHubCollectionGetter
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class GetRepositoryCollectionUseCase <<Interface>> {
    + execute(command: GetRepositoryCollectionCommand): Promise<GetRepositoryCollectionResult>
}

class GetAllRepositoryCollectionsUseCase <<Interface>> {
    + executeAll(command: GetAllRepositoryCollectionsCommand): Promise<GetAllRepositoryCollectionsResult>
}

class IGetAllRepositoryCollectionsPort <<Interface>>
class IGetRepositoryCollectionPort <<Interface>>

class GitHubCollectionGetter {
    - singleCollectionGetter: IGetRepositoryCollectionPort
    - allCollectionGetter: IGetAllRepositoryCollectionsPort
    ---
    + GitHubCollectionGetter(singleCollectionGetter, allCollectionGetter)
    + execute(command: GetRepositoryCollectionCommand): Promise<GetRepositoryCollectionResult>
    + executeAll(command: GetAllRepositoryCollectionsCommand): Promise<GetAllRepositoryCollectionsResult>
}

GitHubCollectionGetter ..up-|> GetRepositoryCollectionUseCase
GitHubCollectionGetter ..up-|> GetAllRepositoryCollectionsUseCase
GitHubCollectionGetter --right-> IGetRepositoryCollectionPort
GitHubCollectionGetter --left-> IGetAllRepositoryCollectionsPort
@enduml