@startuml StartAnalysisService
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

interface StartAnalysisUseCase {
    + execute(command: StartAnalysisCommand): Promise<StartAnalysisResult>
}

class StartAnalysisService {
    - passwordProviderService: IPasswordProvider
    - authorizationService: IRepositoryAuthorizer
    - validatorService: IRepositoryValidator
    - clonerService: IRepositoryCloner
    - orchestrationService: IAnalysisOrchestrator
    - analysisSavePort: IGitHubAnalysisSavePort
    ---
    + StartAnalysisService(passwordProvider, authorizer, validator, cloner, orchestrator, analysisSavePort)
    + execute(command: StartAnalysisCommand): Promise<StartAnalysisResult>
}

StartAnalysisService ..up|> StartAnalysisUseCase
StartAnalysisService --down-> IPasswordProvider
StartAnalysisService --down-> IRepositoryAuthorizer
StartAnalysisService --down-> IRepositoryValidator
StartAnalysisService --down-> IRepositoryCloner
StartAnalysisService --down-> IAnalysisOrchestrator
StartAnalysisService --down-> IGitHubAnalysisSavePort
StartAnalysisService ..down.> GitHubAnalysis
@enduml