@startuml UpdatePatResponseDTO
skinparam componentStyle uml2.5
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam ClassAttributeIconSize 0
hide circles

class UpdatePatResponseDTO {
    + updated: boolean
    + error?: string
    ---
    - UpdatePatResponseDTO(updated, error?)
    + {static} success(): UpdatePatResponseDTO
    + {static} failure(error): UpdatePatResponseDTO
}
@enduml